image: registry.cern.ch/docker.io/ubuntu:jammy

stages:
  - build
    
clang-format:
  stage: build
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y software-properties-common wget cmake git findutils clang-format-14
  script:
    - ln -s `which clang-format-14` clang-format && PATH=$PATH:$PWD ./scripts/clang-format-test.sh
 
# performing the static analysis code check using a custom docker image with the llvm installation we need
code_checks:
  stage: build
  before_script:
    - apt update -y && apt-get upgrade -y
    - apt install -y software-properties-common wget clang-14 libclang-14-dev clang-tidy-14 python3 python-is-python3 cmake git
  script:
    - mkdir build && cd build
    - CXX=clang++-14 cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_ROOT=OFF -DVECGEOM_GDML=OFF -DVECGEOM_TEST_STATIC_ANALYSIS=ON -DVECGEOM_BACKEND=Scalar
    - make -j8
    - ctest -j8 -V
     
# normal build against a recent ROOT; using the ALICE software stack
# Solid model with navigation index
NOSURF_NAVINDEX_ROOT:
   tags:
     - cvmfs
   image: cern/alma9-base
   stage: build
   before_script:
     - yum install -y environment-modules libX11 cmake
     - yum install -y unzip autoconf automake make gcc git harfbuzz-icu
     - eval $(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-28-02-1)
     - export VC_PATH=/cvmfs/alice.cern.ch/el9-x86_64/Packages/Vc/1.4.1-13
     - export CMAKE_PREFIX_PATH=${VC_PATH}:${CMAKE_PREFIX_PATH}
   script:
     - mkdir build && cd build
     - cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_BACKEND=Vc -DVECGEOM_USE_SURF=OFF -DVECGEOM_USE_NAVINDEX=ON -DVECGEOM_USE_NAVTUPLE=OFF -DVECGEOM_ROOT=ON -DVECGEOM_GDML=OFF
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03

# Solid model with navigation tuple
NOSURF_NAVTUPLE_ROOT_GDML:
   tags:
     - cvmfs
   image: cern/alma9-base
   stage: build
   before_script:
     - dnf install -y epel-release
     - yum install -y environment-modules libX11 cmake
     - yum install -y unzip autoconf automake make gcc git harfbuzz-icu xerces-c-devel
     - eval $(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-28-02-1)
     - export VC_PATH=/cvmfs/alice.cern.ch/el9-x86_64/Packages/Vc/1.4.1-13
     - export CMAKE_PREFIX_PATH=${VC_PATH}:${CMAKE_PREFIX_PATH}
   script:
     - mkdir build && cd build
     - cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_BACKEND=Vc -DVECGEOM_USE_SURF=OFF -DVECGEOM_USE_NAVINDEX=OFF -DVECGEOM_USE_NAVTUPLE=ON -DVECGEOM_ROOT=ON -DVECGEOM_GDML=ON
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03

# build for DVECGEOM_GDML=ON (using the cvmfs ALICE software stack: TODO: convert to project/sft...)
NOSURF_NAVPATH_ROOT_GDML:
   tags:
     - cvmfs
   image: cern/alma9-base
   stage: build
   before_script:
     - dnf install -y epel-release
     - yum install -y environment-modules libX11 cmake
     - yum install -y unzip autoconf automake make gcc git harfbuzz-icu xerces-c-devel
     - eval $(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-28-02-1)
     - export VC_PATH=/cvmfs/alice.cern.ch/el9-x86_64/Packages/Vc/1.4.1-13
     - export CMAKE_PREFIX_PATH=${VC_PATH}:${CMAKE_PREFIX_PATH}
   script:
     - mkdir build && cd build
     - cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_BACKEND=Vc -DVECGEOM_USE_SURF=OFF -DVECGEOM_USE_NAVINDEX=OFF -DVECGEOM_USE_NAVTUPLE=OFF -DVECGEOM_ROOT=ON -DVECGEOM_GDML=ON
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03

# build for USING_NAVINDEX=ON and VECGEOM_GDML=ON (using the cvmfs ALICE software stack: TODO: convert to project/sft...)
SURF_NAVINDEX_ROOT_GDML_BENCH_COVERAGE:
   tags:
     - cvmfs
   image: cern/alma9-base
   stage: build
   before_script:
     - dnf install -y epel-release
     - yum install -y environment-modules libX11 cmake
     - yum install -y unzip autoconf automake make gcc git harfbuzz-icu xerces-c-devel
     - eval $(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-28-02-1)
     - export VC_PATH=/cvmfs/alice.cern.ch/el9-x86_64/Packages/Vc/1.4.1-13
     - export CMAKE_PREFIX_PATH=${VC_PATH}:${CMAKE_PREFIX_PATH}
   script:
     - mkdir build && cd build
     - cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_BACKEND=Scalar -DVECGEOM_USE_SURF=ON -DVECGEOM_USE_NAVINDEX=ON -DVECGEOM_USE_NAVTUPLE=OFF -DVECGEOM_ROOT=ON -DVECGEOM_GDML=ON -DVECGEOM_TEST_BENCHMARK=ON -DVECGEOM_TEST_COVERAGE=ON
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03

# build for VECGEOM_USE_SURF=ON  VECGEOM_USE_NAVTUPLE=ON  VECGEOM_NAVTUPLE_MAXDEPTH=4 and VECGEOM_GDML=ON
SURF_NAVTUPLE4_GDML_BENCH_COVERAGE:
   tags:
     - cvmfs
   image: cern/alma9-base
   stage: build
   before_script:
     - dnf install -y epel-release
     - yum install -y environment-modules libX11 cmake
     - yum install -y unzip autoconf automake make gcc git harfbuzz-icu xerces-c-devel
     - eval $(/cvmfs/alice.cern.ch/bin/alienv printenv ROOT::v6-28-02-1)
   script:
     - mkdir build && cd build
     - cmake .. -DVECGEOM_BUILTIN_VECCORE=ON -DVECGEOM_BACKEND=Scalar -DVECGEOM_USE_SURF=ON -DVECGEOM_USE_NAVINDEX=OFF -DVECGEOM_USE_NAVTUPLE=ON -DVECGEOM_NAVTUPLE_MAXDEPTH=4 -DVECGEOM_GDML=ON -DVECGEOM_TEST_BENCHMARK=ON -DVECGEOM_TEST_COVERAGE=ON
       # for the moment exclude the E03 test since downloading E03 root geometry has problems on the CI machine
     - make -j8 VERBOSE=ON && ctest --output-on-failure -j8 -E E03
