/**
 * @file root_manager.h
 * @author Johannes de Fine Licht (johannes.definelicht@cern.ch)
 */

#ifndef VECGEOM_MANAGEMENT_ROOTMANAGER_H_
#define VECGEOM_MANAGEMENT_ROOTMANAGER_H_

#include "base/global.h"

#include "base/type_map.h"

namespace vecgeom {

/**
 * @brief Manager to handle interaction with ROOT geometry.
 * @details Allows integration with ROOT geometries for compatability reasons.
 *          Is not necessary for VecGeom library, and will only have source
 *          compiled if the VECGEOM_ROOT flag is set by the compiler, activated
 *          with -DROOT=ON in CMake.
 */
class RootManager {

private:

  /** Remember pointer to generated world from imported ROOT geometry. */
  VPlacedVolume const* world_ = nullptr;

  TypeMap<VPlacedVolume*, TGeoNode const*> placed_volumes_;
  TypeMap<VUnplacedVolume*, TGeoShape const*> unplaced_volumes_;
  TypeMap<LogicalVolume*, TGeoVolume const*> logical_volumes_;
  TypeMap<TransformationMatrix*, TGeoMatrix const*> matrices_;

public:

  /** Access singleton instance. */
  static RootManager& Instance() {
    static RootManager instance;
    return instance;
  }

  /**
   * @return Most recently generated world from ROOT geometry. Will return NULL
   *         if no ROOT geometry has been imported.
   * @sa LoadRootGeometry()
   */
  VPlacedVolume const* world() const { return world_; }

  TGeoNode const * tgeonode( VPlacedVolume const * p ) const { return placed_volumes_[const_cast<VPlacedVolume*>(p)]; }
  void PrintNodeTable() const;

  /**
   * Queries the global ROOT GeoManager for the top volume and recursively
   * imports and converts to VecGeom geometry.
   * Will register the imported ROOT geometry as the new world of the VecGeom
   * GeoManager singleton.
   */
  void LoadRootGeometry();

  /**
   * Deletes all VecGeom geometry generated by this class.
   */
  void Clear();

  /**
   * Converts a TGeoNode to a VPlacedVolume, recursively converting daughters.
   * Will take care not to convert anything twice by checking the birectional
   * map between ROOT and VecGeom geometry.
   */
  VPlacedVolume* Convert(TGeoNode const *const node);

  VUnplacedVolume* Convert(TGeoShape const *const shape);

  LogicalVolume* Convert(TGeoVolume const *const volume);

  UnplacedBox* Convert(TGeoBBox const *const box);

  TransformationMatrix* Convert(TGeoMatrix const *const matrix);

private:

  RootManager() {}
  RootManager(RootManager const&);
  RootManager& operator=(RootManager const&);

};

} // End namespace vecgeom

#endif // VECGEOM_MANAGEMENT_ROOTMANAGER_H_
