/********************************************************************
* bridges/TGeo/G__UBridges.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error bridges/TGeo/G__UBridges.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__UBridges();
extern void G__cpp_setup_inheritanceG__UBridges();
extern void G__cpp_setup_typetableG__UBridges();
extern void G__cpp_setup_memvarG__UBridges();
extern void G__cpp_setup_globalG__UBridges();
extern void G__cpp_setup_memfuncG__UBridges();
extern void G__cpp_setup_funcG__UBridges();
extern void G__set_cpp_environmentG__UBridges();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGeoUShape.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__UBridgesLN_TClass;
extern G__linked_taginfo G__G__UBridgesLN_TBuffer;
extern G__linked_taginfo G__G__UBridgesLN_TMemberInspector;
extern G__linked_taginfo G__G__UBridgesLN_TObject;
extern G__linked_taginfo G__G__UBridgesLN_TNamed;
extern G__linked_taginfo G__G__UBridgesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__UBridgesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__UBridgesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__UBridgesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__UBridgesLN_TGeoBBox;
extern G__linked_taginfo G__G__UBridgesLN_TGeoShape;
extern G__linked_taginfo G__G__UBridgesLN_VUSolid;
extern G__linked_taginfo G__G__UBridgesLN_TGeoUShape;

/* STUB derived class for protected member access */
